/mission_planner:
  mission_planner:
    ros__parameters:
      distance_to_centerline_threshold: 0.25 # [m] threshold to determine if lane change mission was successful (if ego is in proximity to the goal centerline)
      projection_distance_on_goallane: 20.0 # [m] projection distance of goal point
      retrigger_attempts_max: 10 # number of attempts for triggering a lane change
      local_map_frame: map # Identifier of local map frame. Currently, there is no way to set global ROS params https://github.com/ros2/ros2cli/issues/778 -> This param has to be set in the mission converter also!
