name: create-ros2-package

on:
  workflow_dispatch:
    inputs:
      package-name:
        description: "Name of the ROS 2 package to create"
        required: true
        type: string
      maintainer-email:
        description: "Email of the maintainer"
        required: true
        type: string
      maintainer-name:
        description: "Name of the maintainer"
        required: true
        type: string

jobs:
  create-package:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create ROS 2 package
        run: |
          if [ -d ${{ inputs.package-name }} ]; then
            echo "Package ${{ inputs.package-name }} already exists."
            exit 1
          fi

          mkdir ${{ inputs.package-name }} && cd ${{ inputs.package-name }}

          if [[ "${{ inputs.package-name }}" != *_msgs ]]; then
            mkdir src && touch src/.gitkeep
            mkdir include/${{ inputs.package-name }} && touch include/${{ inputs.package-name }}/.gitkeep
            mkdir launch && touch launch/.gitkeep
            cp ../.template-package/.CMakeLists.txt ./CMakeLists.txt
            cp ../.template-package/.package.xml ./package.xml
          else
            mkdir msg && touch msg/.gitkeep
            cp ../.template-interface-package/.CMakeLists.txt ./CMakeLists.txt
            cp ../.template-interface-package/.package.xml ./package.xml
          fi

          sed 's/__PACKAGE_NAME__/${{ inputs.package-name }}/g' ./CMakeLists.txt > "./CMakeLists.txt.tmp"
          mv "./CMakeLists.txt.tmp" "./CMakeLists.txt"
          sed -e 's/__PACKAGE_NAME__/${{ inputs.package-name }}/g' -e 's/__MAINTAINER_EMAIL__/${{ inputs.maintainer-email }}/g' -e 's/__MAINTAINER_NAME__/${{ inputs.maintainer-name }}/g' ./package.xml > "./package.xml.tmp"
          mv "./package.xml.tmp" "./package.xml"

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          base: ${{ github.event.repository.default_branch }}
          branch: create-package-${{ inputs.package-name }}
          title: "feat: create ${{ inputs.package-name }} package"
          commit-message: "feat: create ${{ inputs.package-name }} package"
          body: "Create ${{ inputs.package-name }} package."
          signoff: true
          delete-branch: true

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"

      - name: Enable auto-merge
        if: ${{ steps.create-pr.outputs.pull-request-operation == 'created' }}
        run: gh pr merge --squash --auto "${{ steps.create-pr.outputs.pull-request-number }}"
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
